/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.uv.HibernateUtil;
import org.uv.data.Departamento;



/**
 *
 * @author leonardo
 */
public class VIDepartamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form VIDepartamento
     */
     //Session session = HibernateUtil.getSessionFactory().getCurrentSession();
     //Transaction t = session.beginTransaction();
     
     Session session = HibernateUtil.getSessionFactory().openSession();
    Transaction t = session.beginTransaction();
     
    String columnas_departamentos [] = {"CLAVE", "NOMBRE"};
    
    public VIDepartamento() {
        initComponents();
        btn_buscar.setEnabled(false);
        btn_guardar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        btn_modificar.setEnabled(false);
        btn_nuevo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_dep_clave = new javax.swing.JTextField();
        tf_dep_nombre = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_buscarTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        war_clave = new javax.swing.JLabel();
        war_nombre = new javax.swing.JLabel();

        jLabel1.setText("Clave");

        jLabel2.setText("Nombre");

        tf_dep_clave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_dep_claveKeyReleased(evt);
            }
        });

        tf_dep_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_dep_nombreKeyReleased(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_buscarTodos.setText("Buscar tods");
        btn_buscarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarTodosActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        war_clave.setForeground(new java.awt.Color(255, 0, 0));
        war_clave.setText("  ");

        war_nombre.setForeground(new java.awt.Color(255, 0, 0));
        war_nombre.setText("  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(war_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_dep_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(tf_dep_clave, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(war_clave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_nuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btn_buscarTodos)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_dep_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(war_clave)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_dep_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(war_nombre))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_buscar)
                            .addComponent(btn_buscarTodos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_nuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btn_guardar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_modificar)))
                .addGap(18, 18, 18)
                .addComponent(btn_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   
    private boolean claveVacio() {
        if (tf_dep_clave.getText().isEmpty()) {
            war_clave.setText("Debe indicar una clave*");
            return true;
        } else {
            war_clave.setText("  ");
            return false;
        }

    }

    private boolean nombreVacio() {
        if (tf_dep_clave.getText().isEmpty()) {
            war_nombre.setText("Debe indicar un nombre*");
            return true;
        } else {
            war_nombre.setText("  ");
            return false;
        }

    }
    
    private void validarTodos() {
        if (tf_dep_clave.getText().isEmpty() || tf_dep_nombre.getText().isEmpty()) {
            btn_buscar.setEnabled(false);
            btn_guardar.setEnabled(false);
            btn_eliminar.setEnabled(false);
            btn_modificar.setEnabled(false);
            btn_nuevo.setEnabled(false);
            
            
        } else {
            btn_guardar.setEnabled(true);
            btn_modificar.setEnabled(true);
            btn_nuevo.setEnabled(true);
            btn_buscar.setEnabled(true);
            btn_eliminar.setEnabled(true);
        }
    }

    private void validarUnCampo() {
        if (tf_dep_clave.getText().isEmpty()) {
            btn_buscar.setEnabled(false);
            btn_guardar.setEnabled(false);
            btn_eliminar.setEnabled(false);
            btn_modificar.setEnabled(false);
            btn_nuevo.setEnabled(false);
        } else {
            btn_buscar.setEnabled(true);
            btn_eliminar.setEnabled(true);
        }
    }

    private void vaciarCampos() {
        tf_dep_clave.setText("");
        tf_dep_nombre.setText("");
    }

    private void validarNuevo() {
        if (!tf_dep_clave.getText().isEmpty() || !tf_dep_nombre.getText().isEmpty()) {
            btn_nuevo.setEnabled(true);
        } else {
            btn_nuevo.setEnabled(false);
        }
    }
    
    private void cargar_departamentos() {
        
        String registros [] = new String[2];
        Query query= session.createQuery("FROM org.uv.data.Departamento");
        List<Departamento> lstQuery = query.list();
        
        DefaultTableModel modelo_departamentos = new DefaultTableModel(columnas_departamentos, 0);
        for (int i = 0; i < lstQuery.size(); i++) {
            registros[0] = String.valueOf(lstQuery.get(i).getClave());
            registros[1] = String.valueOf(lstQuery.get(i).getNombre());
           
           modelo_departamentos.addRow(registros);
        }
        tabla.setModel(modelo_departamentos);
    }
    
    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        Departamento departamento = new Departamento();

        departamento.setClave(Long.parseLong(tf_dep_clave.getText()));
        departamento.setNombre(tf_dep_nombre.getText());

        session.save(departamento);
       Transaction tr = session.beginTransaction();
        tr.commit();
        
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void tf_dep_claveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_dep_claveKeyReleased
        // TODO add your handling code here:
       // validarTodos();
        validarUnCampo();
        validarNuevo();
        
    }//GEN-LAST:event_tf_dep_claveKeyReleased

    private void tf_dep_nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_dep_nombreKeyReleased
        // TODO add your handling code here:
        validarTodos();
        validarUnCampo();
        validarNuevo();
        
    }//GEN-LAST:event_tf_dep_nombreKeyReleased

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:
        vaciarCampos();
        validarTodos();
        validarUnCampo();
        validarNuevo();
        
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
       
       String registros [] = new String[2];
        Query query= session.createQuery("FROM org.uv.data.Departamento where clave='"+tf_dep_clave.getText().toString()+"'");
        List<Departamento> lstQuery = query.list();
        
        DefaultTableModel modelo_departamentos = new DefaultTableModel(columnas_departamentos, 0);
        for (int i = 0; i < lstQuery.size(); i++) {
            registros[0] = String.valueOf(lstQuery.get(i).getClave());
            registros[1] = String.valueOf(lstQuery.get(i).getNombre());
           
           modelo_departamentos.addRow(registros);
        }
        tabla.setModel(modelo_departamentos);
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        session.delete( session.byId( Departamento.class ).getReference( Long.valueOf(tf_dep_clave.getText())) );
        Transaction tr = session.beginTransaction();
        tr.commit();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
        Departamento departamento = new Departamento();
        Transaction tr = session.beginTransaction(); 
        
        departamento.setClave(Long.parseLong(tf_dep_clave.getText()));
        departamento.setNombre(tf_dep_nombre.getText().toString());
        
        session.saveOrUpdate(departamento);
        session.getTransaction().commit();
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_buscarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarTodosActionPerformed
        // TODO add your handling code here:

        cargar_departamentos();

    }//GEN-LAST:event_btn_buscarTodosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_buscarTodos;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField tf_dep_clave;
    private javax.swing.JTextField tf_dep_nombre;
    private javax.swing.JLabel war_clave;
    private javax.swing.JLabel war_nombre;
    // End of variables declaration//GEN-END:variables
}
