/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.uv.HibernateUtil;
import org.uv.data.Empleado;

/**
 *
 * @author leonardo
 */
public class VIEmpleados extends javax.swing.JInternalFrame {

     Session session = HibernateUtil.getSessionFactory().openSession();
    Transaction t = session.beginTransaction();
    
    String columnas_empleados[] = {"CLAVE", "NOMBRE", "DIRECCION", "TELEFONO"};

    public VIEmpleados() {
        initComponents();
        btn_buscar.setEnabled(false);
        btn_buscarTodos.setEnabled(true);
        btn_guardar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        btn_modificar.setEnabled(false);
        btn_nuevo.setEnabled(false);
        
    }

    private boolean claveVacio() {
        if (tf_emp_clave.getText().isEmpty()) {
            war_clave.setText("Debe indicar una clave*");
            return true;
        } else {
            war_clave.setText("  ");
            return false;
        }

    }

    private boolean nombreVacio() {
        if (tf_emp_nombre.getText().isEmpty()) {
            war_nombre.setText("Debe indicar un nombre*");
            return true;
        } else {
            war_nombre.setText("  ");
            return false;
        }

    }

    private boolean direccionVacio() {
        if (tf_emp_direccion.getText().isEmpty()) {
            war_direccion.setText("Debe indicar una direccion*");
            return true;
        } else {
            war_direccion.setText("  ");
            return false;
        }
    }

    private boolean telefonoVacio() {
        if (tf_emp_telefono.getText().isEmpty()) {
            war_telefono.setText("Debe indicar una direccion*");
            return true;
        } else {
            war_telefono.setText("  ");
            return false;
        }
    }

    private void validarTodos() {
        if (tf_emp_clave.getText().isEmpty() || (tf_emp_nombre.getText().isEmpty() || tf_emp_direccion.getText().isEmpty() || tf_emp_telefono.getText().isEmpty())) {
            btn_buscar.setEnabled(false);
            btn_guardar.setEnabled(false);
            btn_eliminar.setEnabled(false);
            btn_modificar.setEnabled(false);
            btn_nuevo.setEnabled(false);
        } else {
            btn_guardar.setEnabled(true);
            btn_modificar.setEnabled(true);
            btn_nuevo.setEnabled(true);
            btn_buscar.setEnabled(true);
            btn_eliminar.setEnabled(true);
        }
    }

    private void validarUnCampo() {
        if (tf_emp_clave.getText().isEmpty()) {
            btn_buscar.setEnabled(false);
            btn_guardar.setEnabled(false);
            btn_eliminar.setEnabled(false);
            btn_modificar.setEnabled(false);
            btn_nuevo.setEnabled(false);
        } else {
            btn_buscar.setEnabled(true);
            btn_eliminar.setEnabled(true);
        }
    }

    private void vaciarCampos() {
        tf_emp_clave.setText("");
        tf_emp_nombre.setText("");
        tf_emp_direccion.setText("");
        tf_emp_telefono.setText("");
    }

    private void validarNuevo() {
        if (!tf_emp_clave.getText().isEmpty() || !tf_emp_nombre.getText().isEmpty() || !tf_emp_direccion.getText().isEmpty() || !tf_emp_telefono.getText().isEmpty()) {
            btn_nuevo.setEnabled(true);
        } else {
            btn_nuevo.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_emp_nombre = new javax.swing.JTextField();
        tf_emp_clave = new javax.swing.JTextField();
        tf_emp_direccion = new javax.swing.JTextField();
        tf_emp_telefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_buscarTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        war_nombre = new javax.swing.JLabel();
        war_clave = new javax.swing.JLabel();
        war_direccion = new javax.swing.JLabel();
        war_telefono = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        tf_emp_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_emp_nombreKeyReleased(evt);
            }
        });

        tf_emp_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emp_claveActionPerformed(evt);
            }
        });
        tf_emp_clave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_emp_claveKeyReleased(evt);
            }
        });

        tf_emp_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_emp_direccionKeyReleased(evt);
            }
        });

        tf_emp_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_emp_telefonoKeyReleased(evt);
            }
        });

        jLabel1.setText("Clave:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Dirección:");

        jLabel4.setText("Telefono:");

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_buscarTodos.setText("Buscar todos");
        btn_buscarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarTodosActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Clave", "Nombre", "Teléfono", "Dirección"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        war_nombre.setForeground(new java.awt.Color(255, 0, 0));
        war_nombre.setText("   ");

        war_clave.setForeground(new java.awt.Color(255, 0, 0));
        war_clave.setText("  ");

        war_direccion.setForeground(new java.awt.Color(255, 0, 0));
        war_direccion.setText("   ");

        war_telefono.setForeground(new java.awt.Color(255, 0, 0));
        war_telefono.setText("   ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 169, Short.MAX_VALUE)
                        .addComponent(war_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel4))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(52, 52, 52)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_emp_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(war_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_emp_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(war_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_emp_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(war_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_emp_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(btn_nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscarTodos))
                    .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_emp_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(war_clave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_emp_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(war_nombre)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_emp_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(war_telefono))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_buscar)
                            .addComponent(btn_buscarTodos))
                        .addGap(18, 18, 18)
                        .addComponent(btn_nuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btn_guardar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 33, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_emp_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(war_direccion)))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargar_empleados() {
        String registros [] = new String[4];
        Query query= session.createQuery("FROM org.uv.data.Empleado");
        List<Empleado> lstQuery = query.list();
        
        DefaultTableModel modelo_empleado = new DefaultTableModel(columnas_empleados, 0);
        for (int i = 0; i < lstQuery.size(); i++) {
            registros[0] = String.valueOf(lstQuery.get(i).getClave());
            registros[1] = String.valueOf(lstQuery.get(i).getNombre());
            registros[2] = String.valueOf(lstQuery.get(i).getDireccion());
            registros[3] = String.valueOf(lstQuery.get(i).getTelefono());
           
           modelo_empleado.addRow(registros);
        }
        tabla.setModel(modelo_empleado);
    }
    



    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
       
        Empleado empleado = new Empleado();

        empleado.setClave(Long.parseLong(tf_emp_clave.getText()));
        empleado.setNombre(tf_emp_nombre.getText());
        empleado.setDireccion(tf_emp_direccion.getText());
        empleado.setTelefono(tf_emp_telefono.getText());
        
        session.save(empleado);
        session.getTransaction().commit();

    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:

        Empleado empleado = new Empleado();
        Transaction t = session.beginTransaction();

        empleado.setClave(Long.parseLong(tf_emp_clave.getText().toString()));
        empleado.setNombre(tf_emp_nombre.getText().toString());
        empleado.setDireccion(tf_emp_direccion.getText().toString());
        empleado.setTelefono(tf_emp_telefono.getText().toString());
        
        session.saveOrUpdate(empleado);
        session.getTransaction().commit();

    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here
        vaciarCampos();
        validarTodos();
        validarUnCampo();
        validarNuevo();

    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:

        String registros [] = new String[4];
        Query query= session.createQuery("FROM org.uv.data.Empleado where clave='"+tf_emp_clave.getText().toString()+"'");
        List<Empleado> lstQuery = query.list();
        
        DefaultTableModel modelo_empleado = new DefaultTableModel(columnas_empleados, 0);
        for (int i = 0; i < lstQuery.size(); i++) {
            registros[0] = String.valueOf(lstQuery.get(i).getClave());
            registros[1] = String.valueOf(lstQuery.get(i).getNombre());
            registros[2] = String.valueOf(lstQuery.get(i).getDireccion());
            registros[3] = String.valueOf(lstQuery.get(i).getTelefono());
           
           modelo_empleado.addRow(registros);
        }
        tabla.setModel(modelo_empleado);
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:

        session.delete( session.byId(Empleado.class ).getReference( Long.valueOf(tf_emp_clave.getText())) );
        Transaction tr = session.beginTransaction();
        tr.commit();

    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void tf_emp_claveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_emp_claveKeyReleased
        // TODO add your handling code here:
        validarTodos();
        validarUnCampo();
        validarNuevo();
    }//GEN-LAST:event_tf_emp_claveKeyReleased

    private void tf_emp_nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_emp_nombreKeyReleased
        // TODO add your handling code here:
        validarTodos();
        validarUnCampo();
        validarNuevo();

    }//GEN-LAST:event_tf_emp_nombreKeyReleased

    private void tf_emp_telefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_emp_telefonoKeyReleased
        // TODO add your handling code here:
        validarTodos();
        validarUnCampo();
        validarNuevo();
    }//GEN-LAST:event_tf_emp_telefonoKeyReleased

    private void tf_emp_direccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_emp_direccionKeyReleased
        // TODO add your handling code here:
        validarTodos();
        validarUnCampo();
        validarNuevo();
    }//GEN-LAST:event_tf_emp_direccionKeyReleased

    private void tf_emp_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emp_claveActionPerformed
        // TODO add your handling code here:
        cargar_empleados();
    }//GEN-LAST:event_tf_emp_claveActionPerformed

    private void btn_buscarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarTodosActionPerformed
        // TODO add your handling code here:
        cargar_empleados();
       
    }//GEN-LAST:event_btn_buscarTodosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_buscarTodos;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField tf_emp_clave;
    private javax.swing.JTextField tf_emp_direccion;
    private javax.swing.JTextField tf_emp_nombre;
    private javax.swing.JTextField tf_emp_telefono;
    private javax.swing.JLabel war_clave;
    private javax.swing.JLabel war_direccion;
    private javax.swing.JLabel war_nombre;
    private javax.swing.JLabel war_telefono;
    // End of variables declaration//GEN-END:variables
}
